SYMBOL_BTC = 'BTC'
SYMBOL_BTC_JPY = 'BTC_JPY'

BUY = 'BUY'
SELL = 'SELL'

DURATION_1M = '1m'
DURATION_5M = '5m'
DURATION_15M = '15m'
DURATION_30M = '30m'
DURATION_1H = '1h'
DURATIONS_ALL = [DURATION_1M, DURATION_5M, DURATION_15M, DURATION_30M, DURATION_1H]

TRADER = 'SYSTEM'
DIFF_JST_FROM_UTC = 9
